[PW-2640] Deserialize the response of dropin into the correct paymentMethod model
Adyen/adyen-dotnet-api-library pull request #347
Opened 2020-11-26 07:13 UTC by AlexandrosMor

## Summary
In this pr we are extending the Newtonsoft JsonConverter with a custom converter to deserialize the payment request with the payment method details class based on the IPaymentMethodDetails interface. This deserializes the paymentmethod based on the type and return the corresponding payment method detail class instance.
## Tested scenarios 

Test the deserialization with payment request and payment method detail class

**Fixed issue**:

2020-11-26 09:48 UTC, Aleffio requested changes

2020-11-26 09:48 UTC, Aleffio commented on Adyen/Util/PaymentMethodDetailsConverter.cs
> +                    paymentMethodDetails = new ApplePayDetails();
```suggestion
                    paymentMethodDetails = new QiwiWalletDetails();
```

2020-11-26 10:29 UTC, Aleffio approved these changes

2020-11-26 14:01 UTC, msilvagarcia approved these changes

2020-11-26 14:14 UTC, merged

2021-01-11 15:21 UTC, deepu105 commented
@AlexandrosMor would it be possible to mark the `PaymentMethod` field with `[JsonConverter(typeof(PaymentMethodDetailsConverter))]` annotation to make this automatic?