Update the card details class based on v68
Adyen/adyen-dotnet-api-library pull request #537
Opened 2021-12-30 12:24 UTC by AlexandrosMor

## Summary

## Tested scenarios

**Fixed issue**:

2022-01-04 10:46 UTC, zaiddreakh submitted a review, later dismissed

2022-01-18 07:14 UTC, wboereboom requested changes
Only file header update is missing. All seems in order apart from that 👍

2022-01-18 07:14 UTC, wboereboom commented on Adyen/Model/Checkout/CardDetails.cs
>  //  Copyright (c) 2020 Adyen B.V.
```suggestion
//  Copyright (c) 2022 Adyen N.V.
```

2022-02-03 14:48 UTC, AlexandrosMor commented
We are pla

2022-02-21 09:35 UTC, wboereboom commented on Adyen/Model/Checkout/CardDetails.cs
> +     /// <summary>
```suggestion
    /// <summary>
```

2022-02-23 08:43 UTC, zaiddreakh approved these changes

2022-04-12 10:56 UTC, wboereboom approved these changes

2022-04-12 12:48 UTC, zaiddreakh approved these changes

2022-04-12 13:01 UTC, merged