Add missing fields for UpdateAccountRequest.cs
Adyen/adyen-dotnet-api-library pull request #563
Opened 2022-02-11 08:42 UTC by AlexandrosMor

**Description**

**Tested scenarios**

**Fixed issue**:  
fixes #542

2022-02-11 09:56 UTC, wboereboom requested changes
1 small  nitpick. 
Also: Do we need to update tests?

2022-02-11 09:56 UTC, wboereboom commented on Adyen/Model/MarketPay/UpdateAccountRequest.cs
> + * Copyright (c) 2021 Adyen N.V.
![image](https://user-images.githubusercontent.com/62436079/153571033-f827a495-edab-4bf2-9c0c-2119a9209016.png)

2022-02-11 13:07 UTC, AlexandrosMor commented on Adyen/Model/MarketPay/UpdateAccountRequest.cs
> + * Copyright (c) 2021 Adyen N.V.
🤣

2022-02-11 13:08 UTC, AlexandrosMor commented on Adyen/Model/MarketPay/UpdateAccountRequest.cs
> + * Copyright (c) 2021 Adyen N.V.
```suggestion
 * Copyright (c) 2022 Adyen N.V.
```

2022-02-15 12:11 UTC, zaiddreakh approved these changes

2022-02-17 09:01 UTC, merged