[PW-6739] Updated KYCVerificationResult Model and added additional
Adyen/adyen-dotnet-api-library pull request #638
Opened 2022-08-08 15:25 UTC by jillingk

Updated KYCVerificationResult models and added additional dependent classes. 

**Description**
KYCVerificationResult was updated and added some other classes that the KYCVerificationResult was depended on. 

**Tested scenarios**
Ran unit tests.

**Fixed issue**: #539

2022-08-09 06:34 UTC, wboereboom requested changes
Looks good to me! Let's look at the LGTM alerts before we merge.

2022-08-09 06:34 UTC, wboereboom commented on Adyen/Model/MarketPay/KYCVerificationResult.cs
> +            sb.Append("  LegalArrangements: ").Append(LegalArrangements).Append("\n");
These objects are not suitable for printing by default and cause the following errors in LGTM:
`Default 'ToString()': List<KYCLegalArrangementEntityCheckResult> inherits 'ToString()' from 'Object', and so is not suitable for printing.`

Let's see if we do this differently for other object fields. If not; we'll fix it in the model templates later.

2022-08-15 12:59 UTC, wboereboom approved these changes

2022-08-17 10:45 UTC, AlexandrosMor approved these changes

2022-08-17 10:45 UTC, merged