[PW-7302] Adding Retrieve3DS2/ClassicPayments and CardDetails/Checkout endpoints
Adyen/adyen-dotnet-api-library pull request #666
Opened 2022-11-10 11:23 UTC by jillingk

**Description**
Added two endpoints that were missing on request of merchants.

**Tested scenarios**
UT

**Fixed issue**:

2022-11-10 15:40 UTC, wboereboom requested changes
Single comment on the tests. Looks good otherwise

2022-11-14 06:11 UTC, AlexandrosMor commented on Adyen/Model/Checkout/CardBrandDetails.cs
> +//  Copyright (c) 2020 Adyen B.V.
Until we remove the headers lets add it to the correct year
```suggestion
//  Copyright (c) 2022 Adyen N.V.
```

2022-11-14 06:11 UTC, AlexandrosMor commented on Adyen/Model/Checkout/CardDetailsRequest.cs
> +//  Copyright (c) 2020 Adyen B.V.
```suggestion
//  Copyright (c) 2022 Adyen N.V.
```

2022-11-14 08:36 UTC, wboereboom approved these changes

2022-11-14 09:10 UTC, AlexandrosMor requested changes

2022-11-14 09:10 UTC, AlexandrosMor commented on Adyen.Test/Adyen.Test.csproj
> +    <Content Include="Mocks\checkout\card-details-success.json" />
Why do we add this specific location in the project file?

2022-11-14 09:10 UTC, AlexandrosMor commented on Adyen/Service/Resource/Payment/Retrieve3DS2Result.cs
> +//  * Copyright (c) 2020 Adyen B.V.
```suggestion
//  * Copyright (c) 2022 Adyen N.V.
```

2022-11-14 09:26 UTC, AlexandrosMor approved these changes

2022-11-14 12:19 UTC, wboereboom approved these changes

2022-11-14 12:25 UTC, merged