update POS Terminal Management and add models to automation
Adyen/adyen-dotnet-api-library pull request #706
Opened 2023-01-04 07:35 UTC by wboereboom

**Description**
Add missing endpoints to POS terminal management service and include models generation in automation scripts

**Tested scenarios**
tested through unit tests

2023-01-04 09:17 UTC, jillingk approved these changes

2023-01-05 11:59 UTC, michaelpaul requested changes

2023-01-05 11:59 UTC, michaelpaul commented on Makefile
> +		--global-property modelDocs=false \
Duplicate line:
```suggestion
```

2023-01-05 12:21 UTC, jillingk commented on Adyen/Service/PosTerminalManagement.cs
> +            var jsonRequest = Util.JsonOperation.SerializeRequest(getStoresUnderAccountRequest);
```suggestion
            var jsonRequest = getStoresUnderAccountRequest.ToJson();
```
Might as well use the model serializer.

2023-01-05 12:22 UTC, jillingk commented on Adyen/Service/PosTerminalManagement.cs
> +            var jsonRequest = Util.JsonOperation.SerializeRequest(getStoresUnderAccountRequest);
```suggestion
            var jsonRequest = getStoresUnderAccountRequest.ToJson();
```
ditto

2023-01-05 14:23 UTC, jillingk submitted a review, later dismissed

2023-01-06 13:36 UTC, michaelpaul approved these changes

2023-01-06 13:38 UTC, jillingk approved these changes

2023-01-06 13:42 UTC, merged