[IT-366] Regenerated BinLookup service/model
Adyen/adyen-dotnet-api-library pull request #748
Opened 2023-02-22 15:34 UTC by jillingk

**Description**
This PR regenerates BinLookup service/model.

2023-02-24 07:37 UTC, wboereboom requested changes
Method names should stay the same

2023-02-28 13:50 UTC, jillingk commented
@wboereboom Can we get this approved? Or is there still an MR open for better method names?

2023-03-07 14:44 UTC, AlexandrosMor approved these changes

2023-03-07 15:21 UTC, wboereboom approved these changes
There is not. :)

2023-03-07 15:21 UTC, merged