[ITT-628] Removed unused endpoints and classic platforms
Adyen/adyen-dotnet-api-library pull request #843
Opened 2023-07-18 14:31 UTC by jillingk

**Description**
This PR removes the config endpoints and resource classes. It also removes classic platforms as it's deprecated and cleans up all the unused classes throughout the library.

2023-07-21 12:31 UTC, michaelpaul approved these changes

2023-07-21 12:32 UTC, michaelpaul requested changes
Please update the readme.

2023-07-21 12:33 UTC, AlexandrosMor approved these changes

2023-07-25 09:32 UTC, michaelpaul approved these changes

2023-07-25 09:53 UTC, wboereboom approved these changes

2023-07-25 10:31 UTC, AlexandrosMor approved these changes

2023-07-25 11:17 UTC, merged