update makefile and readme to upgrade Transfers and Management API
Adyen/adyen-dotnet-api-library pull request #866
Opened 2023-08-18 13:06 UTC by AlexandrosMor

**Description**

**Tested scenarios**

**Fixed issue**:

2023-08-18 14:17 UTC, michaelpaul approved these changes

2023-08-23 13:53 UTC, michaelpaul requested changes
WIP

2023-08-23 13:58 UTC, Aleffio reviewed
minor, let's also update the version of the hateoas links in the mocks
https://github.com/Adyen/adyen-dotnet-api-library/blob/1b6242d50f4921262cbfa66f26fcefd79067b21d/Adyen.Test/mocks/management/list-merchant-accounts.json#L4

2023-08-23 14:17 UTC, AlexandrosMor commented
@Aleffio check again ?

2023-08-23 14:42 UTC, Aleffio submitted a review, later dismissed

2023-08-24 09:37 UTC, michaelpaul approved these changes

2023-08-24 09:39 UTC, michaelpaul requested changes
WIP

2023-10-20 10:12 UTC, Aleffio commented on Makefile
> +ManagmentNotificationService: spec=ManagementNotificationService-v3
```suggestion
ManagementNotificationService: spec=ManagementNotificationService-v3
```

2023-10-20 10:12 UTC, Aleffio commented on Makefile
> +services:=BalanceControl BalancePlatform BinLookup Checkout DataProtection LegalEntityManagement Management Payment Payout PosTerminalManagement Recurring StoredValue Transfers ManagmentNotificationS
```suggestion
services:=BalanceControl BalancePlatform BinLookup Checkout DataProtection LegalEntityManagement Management Payment Payout PosTerminalManagement Recurring StoredValue Transfers ManagementNotificationService BalancePlatformTransferNotification
```

2023-10-23 11:28 UTC, closed without merging